### ISSUE TITLE
Jerky scrolling with large items

### ISSUE THREAD

**Issue by chadananda** [cristovao-trevisan/vue-auto-virtual-scroll-list#22]
As I scroll up or down, when a large item is above the viewport, it messes up scrolling jerking the position up or down. I've tried increasing "extraItems" dramatically but it does not seem to add extra buffer space above the viewport, only below. 

Here is a screen capture showing scrolling slowly down with the scroller getting stuck in a loop as it jerks upwards when the large item leaves the visible area:

https://www.screencast.com/t/J1bWfHXRsm

**Comment by cristovao-trevisan** [comment]
I'll look at it as soon as I can.
Your observation about `extraItems` is correct, it only add items below the viewport (as scrolling up without knowing the items height was not originally supported)

**Comment by chadananda** [comment]
Thanks for all your work. This component has been a big help so far.

**Comment by cristovao-trevisan** [comment]
Can you try the new beta version? (vue-auto-virtual-scroll-list@0.3.0-beta)
Extra items now work backwards.
I also removed the scroll diff compensation, so it will roll up pretty quickly if items didn't render before. I suggest you to change the `defaultHeight` to match your items height as close as possible

**Comment by cristovao-trevisan** [comment]
I initially used scroll diffing (add to scrollTop the difference between the measured height and the defaultHeight), just like [svelte-virtual-list](https://github.com/sveltejs/svelte-virtual-list/blob/master/VirtualList.svelte#L122), but it did not work.
Tried debugging for a few hours and I think this is due to the Vue component lifecycle, which is not the same as the DOM, so I just gave up
